//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winterdom.Workflow.Activities.Msmq.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Winterdom.Workflow.Activities.Msmq.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly receives a message from an MSMQ Queue.
        /// </summary>
        internal static string DirectRecv_Description {
            get {
                return ResourceManager.GetString("DirectRecv_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kind of MSMQ Message Formatter to use.
        /// </summary>
        internal static string Gen_FormatterKind {
            get {
                return ResourceManager.GetString("Gen_FormatterKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMsmqSubscriptionPersistenceService implementation not detected. Please add this service to the WorkflowRuntime.
        /// </summary>
        internal static string IMSPSNotConfigured {
            get {
                return ResourceManager.GetString("IMSPSNotConfigured", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MessageQueuing {
            get {
                object obj = ResourceManager.GetObject("MessageQueuing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqListenerService not configured. Please add this service to the WorkflowRuntime..
        /// </summary>
        internal static string MLServiceNotConfigured {
            get {
                return ResourceManager.GetString("MLServiceNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receives a message from an MSMQ Queue.
        /// </summary>
        internal static string Recv_Description {
            get {
                return ResourceManager.GetString("Recv_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label the message received was marked with.
        /// </summary>
        internal static string Recv_Label {
            get {
                return ResourceManager.GetString("Recv_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message object that was received from the queue.
        /// </summary>
        internal static string Recv_MessageReceived {
            get {
                return ResourceManager.GetString("Recv_MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the message object to expect.
        /// </summary>
        internal static string Recv_MessageType {
            get {
                return ResourceManager.GetString("Recv_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue to receive the message from.
        /// </summary>
        internal static string Recv_Queue {
            get {
                return ResourceManager.GetString("Recv_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a message to an MSMQ Queue.
        /// </summary>
        internal static string Send_Description {
            get {
                return ResourceManager.GetString("Send_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the MSMQ Queue is transactional or not.
        /// </summary>
        internal static string Send_IsTransactionalQueue {
            get {
                return ResourceManager.GetString("Send_IsTransactionalQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label to apply to the message when sending it.
        /// </summary>
        internal static string Send_Label {
            get {
                return ResourceManager.GetString("Send_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message object to send to the queue.
        /// </summary>
        internal static string Send_MessageToSend {
            get {
                return ResourceManager.GetString("Send_MessageToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A send to a transactional queue must be in a transactional scope..
        /// </summary>
        internal static string Send_MustBeInTransaction {
            get {
                return ResourceManager.GetString("Send_MustBeInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue to receive the message from.
        /// </summary>
        internal static string Send_Queue {
            get {
                return ResourceManager.GetString("Send_Queue", resourceCulture);
            }
        }
    }
}
